name: Build and Release

# Every time a new tag with the typical assembly format is pushed this will run. e.g. tag name "1.0.0.0"
on:
  workflow_dispatch:

env:
  # Adjust this to your plugin title
  PLUGIN_NAME: "ASA Tools"

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # In case you need more sub folders add these here
      - name: Prepare folders
        run: |
          mkdir packages
          mkdir packages/${{ PLUGIN_NAME }}

      - name: Get Assembly Version
        id: get_version
        run: |
          $version = (Select-String -Path "Touch-N-Stars/Properties/AssemblyInfo.cs" -Pattern 'AssemblyVersion\("([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)"\)').Matches.Groups[1].Value
          echo "version=$version" >> $env:GITHUB_OUTPUT

      # This will build your solution. If the solution name differs from your plugin name, please adjust it here
      - name: Build .NET Assemblies
        run: |
          dotnet restore
          dotnet build ${{ PLUGIN_NAME }}.sln -c Release -p:PostBuildEvent= -p:Version=${{ steps.get_version.outputs.version }}

      # If you have mkdocs documentation you want to include, you can uncomment and build it like this
      # - name: Build Documentation
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install mkdocs
      #     pip install mkdocs-material
      #     mkdocs build -f ${{ PLUGIN_NAME }}\docs\mkdocs.yml


      # Add all necessary files that the plugin needs to the packages folder - basically all items that are normally in your post build event on your local builds
      - name: Prepare package
        run: |
          Copy-Item "${{ PLUGIN_NAME }}/bin/Release/net8.0-windows/${{ PLUGIN_NAME }}.dll" "packages/${{ PLUGIN_NAME }}/${{ PLUGIN_NAME }}.dll" -Force
          Copy-Item "${{ PLUGIN_NAME }}/bin/Release/net8.0-windows/${{ PLUGIN_NAME }}.pdb" "packages/${{ PLUGIN_NAME }}/${{ PLUGIN_NAME }}.pdb" -Force
      
      - name: Create Plugin archives and manifests
        run: |
          curl https://api.bitbucket.org/2.0/repositories/isbeorn/nina.plugin.manifests/src/main/tools/CreateNET7Manifest.ps1 >> CreateNET7Manifest.ps1
          pwsh CreateNET7Manifest.ps1 -file packages/${{ PLUGIN_NAME }}/${{ PLUGIN_NAME }}.dll -installerUrl https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/${{ PLUGIN_NAME }}.${{ github.ref_name }}.zip -createArchive -includeAll -appendVersionToArchive
          Rename-Item -Path "manifest.json" -NewName "${{ PLUGIN_NAME }}.${{ steps.get_version.outputs.version }}.manifest.json" 

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false
      - name: Upload Plugin Zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ PLUGIN_NAME }}.${{ steps.get_version.outputs.version }}.zip
          asset_name: ${{ PLUGIN_NAME }}.${{ steps.get_version.outputs.version }}.zip
          asset_content_type: application/zip
      - name: Upload Manifest
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ PLUGIN_NAME }}.${{ steps.get_version.outputs.version }}.manifest.json
          asset_name: ${{ PLUGIN_NAME }}.${{ steps.get_version.outputs.version }}.manifest.json
          asset_content_type: application/json